version: '3.9'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - '8080:8080'
    depends_on:
      - mongodb
    environment:
      - PORT=8080
      - MONGODB_URI=mongodb://mongodb:27017/dd_db

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - '80:80'
    depends_on:
      - backend
    environment:
      - API_URL=/api/tutorials

volumes:
  mongo-data:
    driver: local
