version: '3.9'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mean-backend
    restart: unless-stopped
    environment:
      - PORT=8080
      - MONGODB_URL=mongodb://mongodb:27017/dd_db
    depends_on:
      - mongodb
    networks:
      - mean-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mean-frontend
    restart: unless-stopped
    # ❌ remove ports
    environment:
      - API_URL=http://backend:8080
    depends_on:
      - backend
    networks:
      - mean-network

volumes:
  mongo-data:
    driver: local
