name: CI-CD Pipeline

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_REPO: vineethsankre/mean-project
  BACKEND_IMAGE: vineethsankre/mean-project-backend
  FRONTEND_IMAGE: vineethsankre/mean-project-frontend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Login to Docker Hub
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      # Build Backend
      - name: Build Backend Image
        run: |
          docker build -t $BACKEND_IMAGE:${{ github.run_number }} ./backend
          docker build -t $BACKEND_IMAGE:latest ./backend

      # Build Frontend
      - name: Build Frontend Image
        run: |
          docker build -t $FRONTEND_IMAGE:${{ github.run_number }} ./frontend
          docker build -t $FRONTEND_IMAGE:latest ./frontend

      # Push Images
      - name: Push Images
        run: |
          docker push $BACKEND_IMAGE:${{ github.run_number }}
          docker push $BACKEND_IMAGE:latest
          docker push $FRONTEND_IMAGE:${{ github.run_number }}
          docker push $FRONTEND_IMAGE:latest

      # Deploy to VM
      - name: Deploy to VM
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          port: 22
          script: |
            cd ~/MEAN-Stack-DevOps-Project
            docker-compose pull
            docker-compose up -d
            docker system prune -f
